name: Build iOS App
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build App
        run: |
          # Compile the project as an unsigned archive
          xcodebuild archive \
            -scheme SwingMusicApp \
            -destination "generic/platform=iOS" \
            -archivePath ./build/SwingMusicApp.xcarchive \
            CODE_SIGNING_ALLOWED=NO

      - name: Package .app into .ipa
        run: |
          mkdir -p Payload
          cp -r ./build/SwingMusicApp.xcarchive/Products/Applications/*.app ./Payload/
          zip -r SwingMusicApp.ipa Payload

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Build
          path: SwingMusicApp.ipa
